#!/bin/sh


################################## FUNCTIONS ##################################

# Removes specified file (if present).
remove_resource () {
    if [ -e "$1" ]; then
        if  echo "$1" | /usr/bin/grep -q ".plist"; then
            PLIST_LABEL=$(/usr/bin/basename "$1" | /usr/bin/awk -F.plist '{print $1}')
            # If plist is loaded as a LaunchDaemon,
            # remove the launchd task before file deletion.
            if /bin/launchctl list | /usr/bin/grep -q "$PLIST_LABEL"; then
                /bin/launchctl remove "$PLIST_LABEL"
                echo "Removed LaunchDaemon: ${PLIST_LABEL}"
            fi
        fi
        /bin/rm -rf "$1"
        echo "Deleted file: ${1}"
    fi
}


################################ MAIN PROCESS #################################

# Kill jamfHelper process to close any current notifications.
echo "Killing any active jamfHelper notifications..."
/usr/bin/killall jamfHelper 2>"/dev/null"

# Remove all script resources (if present).
echo "Removing existing script resources..."
remove_resource "${3}/Library/LaunchDaemons/com.github.mpanighetti.install-or-defer.plist"
remove_resource "${3}/Library/Preferences/com.github.mpanighetti.install-or-defer.plist"
remove_resource "${3}/Library/Scripts/Install or Defer.sh"
remove_resource "${3}/Library/Scripts/Install or Defer_helper.sh"
remove_resource "${3}/private/tmp/install-or-defer"
