#!/bin/bash

RESOURCE_FILES=(
    "$3/Library/LaunchDaemons/com.elliotjordan.install_or_defer.plist"
    "$3/Library/LaunchDaemons/com.github.mpanighetti.install-or-defer.plist"
    "$3/Library/Preferences/com.elliotjordan.install_or_defer.plist"
    "$3/Library/Preferences/com.github.mpanighetti.install-or-defer.plist"
    "$3/Library/Scripts/install_or_defer.sh"
    "$3/Library/Scripts/Install or Defer.sh"
    "$3/Library/Scripts/install_or_defer_helper.sh"
    "$3/Library/Scripts/Install or Defer_helper.sh"
    "$3/private/tmp/install-or-defer"
)

# Kill jamfHelper process to close all current notifications.
echo "Killing any active jamfHelper notifications..."
/usr/bin/killall jamfHelper 2>"/dev/null"

# Clear out legacy package receipt (if present).
if [[ $(/usr/sbin/pkgutil --pkgs) == *"com.elliotjordan.install_or_defer"* ]]; then
    /usr/sbin/pkgutil --forget "com.elliotjordan.install_or_defer"
fi

# Remove all script resources (if already present on the system).
echo "Removing existing script resources..."
for TARGET_FILE in "${RESOURCE_FILES[@]}"; do
    if [[ -e "$TARGET_FILE" ]]; then
        # If plist is loaded as a LaunchDaemon, unload it.
        if [[ "$TARGET_FILE" == *".plist" ]]; then
            PLIST_LABEL=$(/usr/bin/basename "$TARGET_FILE" | /usr/bin/awk -F.plist '{print $1}')
            if [[ $(/bin/launchctl list) == *"$PLIST_LABEL"* ]]; then
                /bin/launchctl remove "$PLIST_LABEL"
                echo "Removed LaunchDaemon: $PLIST_LABEL"
            fi
        fi
        /bin/rm -rf "$TARGET_FILE"
        echo "Deleted file: $TARGET_FILE"
    fi
done
